import Foundation

let suites: [TestSuite] = [
    promptBuilderTests(),
    templateTests(),
    chunkerTests(),
    vectorStoreTests(),
    chatCodableTests(),
    characterPersonaTests(),
    characterCardImporterTests(),
    turnVariantTests(),
    worldInfoEntryCodableTests(),
    worldInfoInjectorTests(),
    memoryAuditRegressionTests(),
    helpIndexTests(),
    settingsServersCodableTests(),
    koboldClientRegistryTests(),
    retrievalEngineRoutingTests(),
    serverEditingTests(),
    serverProbeParseTests(),
    chatServerPickerTests(),
    avatarSourceTests(),
    speakerTests(),
    kokoroVoiceCatalogueTests(),
    kokoroStoragePathsTests(),
    voiceStorageScoutTests(),
    kokoroManifestTests(),
    kokoroModelStoreTests(),
    voiceStoragePromptTests(),
    kokoroDownloadTypesTests(),
    espeakNgTests(),
    minimalZipReaderTests(),
    kokoroVoiceFileTests(),
    espeakNgClientTests(),
    kokoroTokenizerTests(),
]

exit(TestRunner.run(suites))
