import Foundation

let suites: [TestSuite] = [
    promptBuilderTests(),
    templateTests(),
    chunkerTests(),
    vectorStoreTests(),
    chatCodableTests(),
    characterPersonaTests(),
    characterCardImporterTests(),
    turnVariantTests(),
    worldInfoEntryCodableTests(),
    worldInfoInjectorTests(),
    memoryAuditRegressionTests(),
    helpIndexTests(),
    settingsServersCodableTests(),
    koboldClientRegistryTests(),
    retrievalEngineRoutingTests(),
    serverEditingTests(),
    serverProbeParseTests(),
    chatServerPickerTests(),
    avatarSourceTests(),
    speakerTests(),
    kokoroVoiceCatalogueTests(),
    kokoroStoragePathsTests(),
    voiceStorageScoutTests(),
    kokoroManifestTests(),
    kokoroModelStoreTests(),
    voiceStoragePromptTests(),
    kokoroDownloadTypesTests(),
    espeakNgTests(),
    minimalZipReaderTests(),
    kokoroVoiceFileTests(),
    espeakNgClientTests(),
    kokoroTokenizerTests(),
    kokoroTokenChunkerTests(),
    voiceIdentifierTests(),
    voicePreferenceTests(),
    entityVoiceTests(),
    chatSettingsVoiceTests(),
    voicePickerSourceTests(),
    speakerAttributionTests(),
    chatBranchingTests(),
    sceneSummaryMigrationTests(),
    chunkBranchingTests(),
    retrievalEngineBranchingTests(),
    minimapLayoutTests(),
    phase8MigrationTests(),
    speakerPickerTests(),
    promptBuilderGroupChatTests(),
    directorPickerTests(),
    phase9CharacterTests(),
    characterCardExporterTests(),
    phase9RoundtripTests(),
    phase9DesignTokensTests(),
    phase9CharacterDraftTests(),
    phase9bHelpersTests(),
    phase9cTagsPersistTests(),
    phase9cStructuredDetailsTests(),
    phase9dExemplarsTests(),
    phase9dCardFieldGraphTests(),
    phase9dRefusalDetectorTests(),
    phase9dPromptBuilderTests(),
    phase9dSideCallTests(),
    phase9dControllerTests(),
    phase9eMultiFieldTests(),
    phase9eOrchestratorTests(),
    phase9fAutopilotOrchestratorTests(),
    phase9fProposalReviewModelTests(),
    phase9fProposalReviewSectionTests(),
    smokeFixturesTests(),
    modelObservationLogTests(),
    quirkDetectorsTests(),
    modelCapabilitiesTests(),
    promptBuilderOverridesTests(),
    placeholderSubstitutionTests(),
    characterEntitySeedTests(),
]

// `TestRunner.run` is `@MainActor`-isolated so test bodies can drive
// MainActor-bound types. Top-level main.swift code isn't actor-
// isolated by default, but executables run their main on the main
// thread, so `assumeIsolated` is the right hop.
exit(MainActor.assumeIsolated { TestRunner.run(suites) })
